/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.sliit.csse.group19.gui;

/**
 *
 * @author Muhammed Suhail
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
//        this.setLocationRelativeTo(null);
        initComponents();
        this.PaymentButton.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SubPanels = new javax.swing.JLayeredPane();
        PaymentTabber = new javax.swing.JTabbedPane();
        SuccessfulPaymentTabber = new javax.swing.JTabbedPane();
        ManagementTabber = new javax.swing.JTabbedPane();
        PendingTabber = new javax.swing.JTabbedPane();
        PaymentPanel = new javax.swing.JPanel();
        EmployeePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SitePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ItemPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SupplierPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HeaderPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        PaymentButton = new javax.swing.JButton();
        SupplierButton = new javax.swing.JButton();
        SiteButton = new javax.swing.JButton();
        ItemButton = new javax.swing.JButton();
        EmployeeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        MainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubPanels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaymentTabber.addTab("tab1", SuccessfulPaymentTabber);
        PaymentTabber.addTab("tab1", ManagementTabber);
        PaymentTabber.addTab("tab1", PendingTabber);

        SubPanels.add(PaymentTabber, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 590));

        MainPanel.add(SubPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1040, 600));

        javax.swing.GroupLayout PaymentPanelLayout = new javax.swing.GroupLayout(PaymentPanel);
        PaymentPanel.setLayout(PaymentPanelLayout);
        PaymentPanelLayout.setHorizontalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        PaymentPanelLayout.setVerticalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        MainPanel.add(PaymentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 110, 1030, 590));

        jLabel3.setText("employee");

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel3)
                .addContainerGap(672, Short.MAX_VALUE))
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel3)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        MainPanel.add(EmployeePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        jLabel4.setText("site");

        javax.swing.GroupLayout SitePanelLayout = new javax.swing.GroupLayout(SitePanel);
        SitePanel.setLayout(SitePanelLayout);
        SitePanelLayout.setHorizontalGroup(
            SitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SitePanelLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel4)
                .addContainerGap(693, Short.MAX_VALUE))
        );
        SitePanelLayout.setVerticalGroup(
            SitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SitePanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel4)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        MainPanel.add(SitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        jLabel2.setText("items");

        javax.swing.GroupLayout ItemPanelLayout = new javax.swing.GroupLayout(ItemPanel);
        ItemPanel.setLayout(ItemPanelLayout);
        ItemPanelLayout.setHorizontalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel2)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        ItemPanelLayout.setVerticalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        MainPanel.add(ItemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        jLabel1.setText("supplier");

        javax.swing.GroupLayout SupplierPanelLayout = new javax.swing.GroupLayout(SupplierPanel);
        SupplierPanel.setLayout(SupplierPanelLayout);
        SupplierPanelLayout.setHorizontalGroup(
            SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SupplierPanelLayout.createSequentialGroup()
                    .addGap(501, 501, 501)
                    .addComponent(jLabel1)
                    .addContainerGap(492, Short.MAX_VALUE)))
        );
        SupplierPanelLayout.setVerticalGroup(
            SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SupplierPanelLayout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(jLabel1)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        MainPanel.add(SupplierPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 105, 1030, 590));

        HeaderPanel.setBackground(new java.awt.Color(255, 255, 255));

        HeaderLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 870, 90));

        PaymentButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PaymentButton.setText("Payments");
        PaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentButtonActionPerformed(evt);
            }
        });
        MainPanel.add(PaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 165, 50));

        SupplierButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SupplierButton.setText("Suppliers");
        SupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierButtonActionPerformed(evt);
            }
        });
        MainPanel.add(SupplierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 165, 48));

        SiteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SiteButton.setText("Sites");
        SiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiteButtonActionPerformed(evt);
            }
        });
        MainPanel.add(SiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 165, 50));

        ItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ItemButton.setText("Items");
        ItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 165, 50));

        EmployeeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployeeButton.setText("Employees");
        EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonActionPerformed(evt);
            }
        });
        MainPanel.add(EmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 165, 50));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemButtonActionPerformed
        // TODO add your handling code here:
        changePanel(1);
    }//GEN-LAST:event_ItemButtonActionPerformed

    private void PaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentButtonActionPerformed
        // TODO add your handling code here:
//        changePanel(0);
        changePanel(5);
    }//GEN-LAST:event_PaymentButtonActionPerformed

    private void SupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierButtonActionPerformed
        // TODO add your handling code here:
        changePanel(2);
    }//GEN-LAST:event_SupplierButtonActionPerformed

    private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonActionPerformed
        // TODO add your handling code here:
        changePanel(3);
    }//GEN-LAST:event_EmployeeButtonActionPerformed

    private void SiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiteButtonActionPerformed
        // TODO add your handling code here:
        changePanel(4);
    }//GEN-LAST:event_SiteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    private void changePanel(int id) {
        switch (id) {
            case 0:
                this.HeaderLabel.setText("Payment");
                this.PaymentPanel.setVisible(true);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 1:
                this.HeaderLabel.setText("Item");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(true);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 2:
                this.HeaderLabel.setText("Supplier");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(true);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 3:
                this.HeaderLabel.setText("Employee");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(true);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 4:
                this.HeaderLabel.setText("Site");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(true);
                this.PaymentTabber.setVisible(false);
                break;
            case 5:
                this.HeaderLabel.setText("Payment");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(true);
                break;
            default:
                System.out.println(id);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JButton ItemButton;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTabbedPane ManagementTabber;
    private javax.swing.JButton PaymentButton;
    private javax.swing.JPanel PaymentPanel;
    private javax.swing.JTabbedPane PaymentTabber;
    private javax.swing.JTabbedPane PendingTabber;
    private javax.swing.JButton SiteButton;
    private javax.swing.JPanel SitePanel;
    private javax.swing.JLayeredPane SubPanels;
    private javax.swing.JTabbedPane SuccessfulPaymentTabber;
    private javax.swing.JButton SupplierButton;
    private javax.swing.JPanel SupplierPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
