/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.sliit.csse.group19.gui;

/**
 *
 * @author Muhammed Suhail
 */
public class ManagerDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AccountDashBoard
     */
    public ManagerDashBoard() {
        initComponents();
        this.PaymentButton.doClick();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SupplierPanel = new javax.swing.JPanel();
        CurrentSupplierPanel = new javax.swing.JPanel();
        SelectSupplierLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SupplierList = new javax.swing.JList<>();
        SupplierAddUpdatePanel = new javax.swing.JPanel();
        AddUpdateLabel1 = new javax.swing.JLabel();
        SupplierNameTextField1 = new javax.swing.JTextField();
        SupplierEmailTextField = new javax.swing.JTextField();
        SupplierBankNoTextField = new javax.swing.JTextField();
        SupplierAddressTextField = new javax.swing.JTextField();
        SupplierNameLabel = new javax.swing.JLabel();
        SupplierAddressLabel = new javax.swing.JLabel();
        SupplierBankNoLabel = new javax.swing.JLabel();
        SupplierEmailLabel = new javax.swing.JLabel();
        SupplierPhoneLabel = new javax.swing.JLabel();
        AddNewSupplierButton = new javax.swing.JButton();
        SupplierUpdateButton = new javax.swing.JButton();
        SupplierPhoneNoTextField = new javax.swing.JTextField();
        SitePanel = new javax.swing.JPanel();
        CurrentSitePanel = new javax.swing.JPanel();
        SelectSiteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SiteList = new javax.swing.JList<>();
        SiteAddUpdatePanel = new javax.swing.JPanel();
        AddUpdateLabel = new javax.swing.JLabel();
        SiteNameTextField = new javax.swing.JTextField();
        SiteAddressTextField = new javax.swing.JTextField();
        SiteStorageCapacityTextField = new javax.swing.JTextField();
        SiteCurrentCapacityTextField = new javax.swing.JTextField();
        SiteManagerComboBox = new javax.swing.JComboBox<>();
        SiteNameLabel = new javax.swing.JLabel();
        SiteAddressLabel = new javax.swing.JLabel();
        SiteStorageCapacityLabel = new javax.swing.JLabel();
        SiteCurrentCapacityLabel = new javax.swing.JLabel();
        SiteManagerLabel = new javax.swing.JLabel();
        AddNewSiteButton = new javax.swing.JButton();
        SiteUpdateButton = new javax.swing.JButton();
        ItemPanel = new javax.swing.JPanel();
        ItemsScrollPane = new javax.swing.JScrollPane();
        ItemResultTable = new javax.swing.JTable();
        AddNewItemPanel = new javax.swing.JPanel();
        RestrictedLabelItem = new javax.swing.JLabel();
        InformationLabelItem = new javax.swing.JLabel();
        PriceLabelItem = new javax.swing.JLabel();
        CategoryLabelItem = new javax.swing.JLabel();
        ItemNameLabelItem = new javax.swing.JLabel();
        ItemNameTextField = new javax.swing.JTextField();
        CategoryComboBox = new javax.swing.JComboBox<>();
        PriceTextField = new javax.swing.JTextField();
        InformationTextField = new javax.swing.JTextField();
        RestrictedCheckBox = new javax.swing.JCheckBox();
        SubHeaderLabelItem = new javax.swing.JLabel();
        AddItemButton = new javax.swing.JButton();
        SearchItemTextfieldItem = new javax.swing.JTextField();
        SearchItemButtonItem = new javax.swing.JButton();
        EmployeePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        SubPanels = new javax.swing.JLayeredPane();
        PaymentTabber = new javax.swing.JTabbedPane();
        SuccessfulPaymentTabber = new javax.swing.JTabbedPane();
        ManagementTabber = new javax.swing.JTabbedPane();
        PendingTabber = new javax.swing.JTabbedPane();
        PaymentPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        PaymentButton = new javax.swing.JButton();
        SupplierButton = new javax.swing.JButton();
        SiteButton = new javax.swing.JButton();
        ItemButton = new javax.swing.JButton();
        EmployeeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        MainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectSupplierLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectSupplierLabel.setText("Select Supplier");

        SupplierList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(SupplierList);

        SupplierAddUpdatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        AddUpdateLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        AddUpdateLabel1.setText("Add / Update Supplier Details");

        SupplierNameTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SupplierEmailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SupplierBankNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SupplierAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SupplierNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierNameLabel.setText("Site Name");

        SupplierAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierAddressLabel.setText("Address");

        SupplierBankNoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierBankNoLabel.setText("Bank Account No");

        SupplierEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierEmailLabel.setText("Email");

        SupplierPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierPhoneLabel.setText("Phone");

        AddNewSupplierButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddNewSupplierButton.setText("Add new site");

        SupplierUpdateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SupplierUpdateButton.setText("Update");

        SupplierPhoneNoTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout SupplierAddUpdatePanelLayout = new javax.swing.GroupLayout(SupplierAddUpdatePanel);
        SupplierAddUpdatePanel.setLayout(SupplierAddUpdatePanelLayout);
        SupplierAddUpdatePanelLayout.setHorizontalGroup(
            SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierAddUpdatePanelLayout.createSequentialGroup()
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SupplierAddUpdatePanelLayout.createSequentialGroup()
                        .addContainerGap(333, Short.MAX_VALUE)
                        .addComponent(SupplierUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddNewSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SupplierAddUpdatePanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierNameLabel)
                            .addComponent(SupplierAddressLabel)
                            .addComponent(SupplierBankNoLabel)
                            .addComponent(SupplierEmailLabel)
                            .addComponent(SupplierPhoneLabel))
                        .addGap(60, 60, 60)
                        .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierEmailTextField)
                            .addComponent(SupplierNameTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SupplierAddressTextField)
                            .addComponent(SupplierBankNoTextField)
                            .addComponent(SupplierPhoneNoTextField))))
                .addGap(99, 99, 99))
            .addGroup(SupplierAddUpdatePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AddUpdateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SupplierAddUpdatePanelLayout.setVerticalGroup(
            SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierAddUpdatePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AddUpdateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierBankNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierBankNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierEmailLabel))
                .addGap(18, 18, 18)
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierPhoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierPhoneLabel))
                .addGap(37, 37, 37)
                .addGroup(SupplierAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CurrentSupplierPanelLayout = new javax.swing.GroupLayout(CurrentSupplierPanel);
        CurrentSupplierPanel.setLayout(CurrentSupplierPanelLayout);
        CurrentSupplierPanelLayout.setHorizontalGroup(
            CurrentSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentSupplierPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CurrentSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectSupplierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SupplierAddUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CurrentSupplierPanelLayout.setVerticalGroup(
            CurrentSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentSupplierPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(CurrentSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupplierAddUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CurrentSupplierPanelLayout.createSequentialGroup()
                        .addComponent(SelectSupplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout SupplierPanelLayout = new javax.swing.GroupLayout(SupplierPanel);
        SupplierPanel.setLayout(SupplierPanelLayout);
        SupplierPanelLayout.setHorizontalGroup(
            SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SupplierPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CurrentSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        SupplierPanelLayout.setVerticalGroup(
            SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SupplierPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(CurrentSupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );

        MainPanel.add(SupplierPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        SelectSiteLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelectSiteLabel.setText("Select Site");

        SiteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(SiteList);

        SiteAddUpdatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        AddUpdateLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        AddUpdateLabel.setText("Add / Update Site Details");

        SiteNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SiteAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SiteStorageCapacityTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SiteCurrentCapacityTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SiteManagerComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiteManagerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SiteNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiteNameLabel.setText("Site Name");

        SiteAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiteAddressLabel.setText("Address");

        SiteStorageCapacityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiteStorageCapacityLabel.setText("Storage Capacity");

        SiteCurrentCapacityLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiteCurrentCapacityLabel.setText("Current Capacity");

        SiteManagerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiteManagerLabel.setText("Site Manager");

        AddNewSiteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddNewSiteButton.setText("Add new site");

        SiteUpdateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SiteUpdateButton.setText("Update");

        javax.swing.GroupLayout SiteAddUpdatePanelLayout = new javax.swing.GroupLayout(SiteAddUpdatePanel);
        SiteAddUpdatePanel.setLayout(SiteAddUpdatePanelLayout);
        SiteAddUpdatePanelLayout.setHorizontalGroup(
            SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiteAddUpdatePanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SiteAddUpdatePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(SiteUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddNewSiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SiteAddUpdatePanelLayout.createSequentialGroup()
                        .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SiteNameLabel)
                            .addComponent(SiteAddressLabel)
                            .addComponent(SiteStorageCapacityLabel)
                            .addComponent(SiteCurrentCapacityLabel)
                            .addComponent(SiteManagerLabel))
                        .addGap(60, 60, 60)
                        .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SiteAddressTextField)
                            .addComponent(SiteNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SiteCurrentCapacityTextField)
                            .addComponent(SiteStorageCapacityTextField)
                            .addComponent(SiteManagerComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(99, 99, 99))
            .addGroup(SiteAddUpdatePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AddUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SiteAddUpdatePanelLayout.setVerticalGroup(
            SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiteAddUpdatePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(AddUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteCurrentCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteStorageCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteStorageCapacityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteCurrentCapacityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteManagerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiteManagerLabel))
                .addGap(38, 38, 38)
                .addGroup(SiteAddUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiteUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewSiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CurrentSitePanelLayout = new javax.swing.GroupLayout(CurrentSitePanel);
        CurrentSitePanel.setLayout(CurrentSitePanelLayout);
        CurrentSitePanelLayout.setHorizontalGroup(
            CurrentSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentSitePanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(CurrentSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectSiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SiteAddUpdatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CurrentSitePanelLayout.setVerticalGroup(
            CurrentSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentSitePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(CurrentSitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SiteAddUpdatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CurrentSitePanelLayout.createSequentialGroup()
                        .addComponent(SelectSiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout SitePanelLayout = new javax.swing.GroupLayout(SitePanel);
        SitePanel.setLayout(SitePanelLayout);
        SitePanelLayout.setHorizontalGroup(
            SitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
            .addGroup(SitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SitePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CurrentSitePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        SitePanelLayout.setVerticalGroup(
            SitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(SitePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SitePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(CurrentSitePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        MainPanel.add(SitePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        ItemResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ItemsScrollPane.setViewportView(ItemResultTable);

        AddNewItemPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        AddNewItemPanel.setToolTipText("");

        RestrictedLabelItem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RestrictedLabelItem.setText("Restricted");

        InformationLabelItem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        InformationLabelItem.setText("Information");

        PriceLabelItem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        PriceLabelItem.setText("Price");

        CategoryLabelItem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CategoryLabelItem.setText("Category");

        ItemNameLabelItem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ItemNameLabelItem.setText("Item Name");

        ItemNameTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        CategoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PriceTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        InformationTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        RestrictedCheckBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        SubHeaderLabelItem.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        SubHeaderLabelItem.setText("Add New Item");

        AddItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddItemButton.setText("Add");

        javax.swing.GroupLayout AddNewItemPanelLayout = new javax.swing.GroupLayout(AddNewItemPanel);
        AddNewItemPanel.setLayout(AddNewItemPanelLayout);
        AddNewItemPanelLayout.setHorizontalGroup(
            AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubHeaderLabelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemNameLabelItem)
                            .addComponent(CategoryLabelItem)
                            .addComponent(RestrictedLabelItem))
                        .addGap(40, 40, 40)
                        .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                                .addComponent(RestrictedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                                .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CategoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceLabelItem)
                                    .addComponent(InformationLabelItem))
                                .addGap(35, 35, 35)
                                .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PriceTextField)
                                    .addComponent(InformationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddNewItemPanelLayout.setVerticalGroup(
            AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubHeaderLabelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemNameLabelItem))
                        .addGap(18, 18, 18)
                        .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoryLabelItem)))
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceLabelItem))
                        .addGap(18, 18, 18)
                        .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InformationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InformationLabelItem))))
                .addGroup(AddNewItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(AddItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(RestrictedLabelItem))
                    .addGroup(AddNewItemPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RestrictedCheckBox)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        SearchItemTextfieldItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchItemTextfieldItem.setText("Search Item");
        SearchItemTextfieldItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchItemTextfieldItemMouseClicked(evt);
            }
        });
        SearchItemTextfieldItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchItemTextfieldItemActionPerformed(evt);
            }
        });

        SearchItemButtonItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchItemButtonItem.setText("Search");

        javax.swing.GroupLayout ItemPanelLayout = new javax.swing.GroupLayout(ItemPanel);
        ItemPanel.setLayout(ItemPanelLayout);
        ItemPanelLayout.setHorizontalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                    .addComponent(AddNewItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(SearchItemTextfieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchItemButtonItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ItemPanelLayout.setVerticalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddNewItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchItemTextfieldItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchItemButtonItem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(ItemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout EmployeePanelLayout = new javax.swing.GroupLayout(EmployeePanel);
        EmployeePanel.setLayout(EmployeePanelLayout);
        EmployeePanelLayout.setHorizontalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(EmployeePanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EmployeePanelLayout.setVerticalGroup(
            EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(EmployeePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        SubPanels.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaymentTabber.addTab("tab1", SuccessfulPaymentTabber);
        PaymentTabber.addTab("tab1", ManagementTabber);
        PaymentTabber.addTab("tab1", PendingTabber);

        SubPanels.add(PaymentTabber, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 590));

        MainPanel.add(SubPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1030, 590));

        javax.swing.GroupLayout PaymentPanelLayout = new javax.swing.GroupLayout(PaymentPanel);
        PaymentPanel.setLayout(PaymentPanelLayout);
        PaymentPanelLayout.setHorizontalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        PaymentPanelLayout.setVerticalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        MainPanel.add(PaymentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 110, 1030, 590));

        HeaderPanel.setBackground(new java.awt.Color(255, 255, 255));

        HeaderLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 870, 90));

        PaymentButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PaymentButton.setText("Payments");
        PaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentButtonActionPerformed(evt);
            }
        });
        MainPanel.add(PaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 165, 50));

        SupplierButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SupplierButton.setText("Suppliers");
        SupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierButtonActionPerformed(evt);
            }
        });
        MainPanel.add(SupplierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 165, 48));

        SiteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SiteButton.setText("Sites");
        SiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiteButtonActionPerformed(evt);
            }
        });
        MainPanel.add(SiteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 165, 50));

        ItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ItemButton.setText("Items");
        ItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 165, 50));

        EmployeeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployeeButton.setText("Employees");
        EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonActionPerformed(evt);
            }
        });
        MainPanel.add(EmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 165, 50));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchItemTextfieldItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchItemTextfieldItemMouseClicked
        // TODO add your handling code here:
        this.SearchItemTextfieldItem.setText("");
    }//GEN-LAST:event_SearchItemTextfieldItemMouseClicked

    private void SearchItemTextfieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchItemTextfieldItemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SearchItemTextfieldItemActionPerformed

    private void PaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentButtonActionPerformed
        // TODO add your handling code here:
        //        changePanel(0);
        changePanel(5);
    }//GEN-LAST:event_PaymentButtonActionPerformed

    private void SupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierButtonActionPerformed
        // TODO add your handling code here:
        changePanel(2);
    }//GEN-LAST:event_SupplierButtonActionPerformed

    private void SiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiteButtonActionPerformed
        // TODO add your handling code here:
        changePanel(4);
    }//GEN-LAST:event_SiteButtonActionPerformed

    private void ItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemButtonActionPerformed
        // TODO add your handling code here:
        changePanel(1);
    }//GEN-LAST:event_ItemButtonActionPerformed

    private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonActionPerformed
        // TODO add your handling code here:
        changePanel(3);
    }//GEN-LAST:event_EmployeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashBoard().setVisible(true);
            }
        });
    }
    
        private void changePanel(int id) {
        switch (id) {
            case 0:
                this.HeaderLabel.setText("Payment");
                this.PaymentPanel.setVisible(true);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 1:
                this.HeaderLabel.setText("Item");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(true);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 2:
                this.HeaderLabel.setText("Supplier");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(true);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 3:
                this.HeaderLabel.setText("Employee");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(true);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(false);
                break;
            case 4:
                this.HeaderLabel.setText("Site");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(true);
                this.PaymentTabber.setVisible(false);
                break;
            case 5:
                this.HeaderLabel.setText("Payment");
                this.PaymentPanel.setVisible(false);
                this.ItemPanel.setVisible(false);
                this.SupplierPanel.setVisible(false);
                this.EmployeePanel.setVisible(false);
                this.SitePanel.setVisible(false);
                this.PaymentTabber.setVisible(true);
                break;
            default:
                System.out.println(id);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JPanel AddNewItemPanel;
    private javax.swing.JButton AddNewSiteButton;
    private javax.swing.JButton AddNewSupplierButton;
    private javax.swing.JLabel AddUpdateLabel;
    private javax.swing.JLabel AddUpdateLabel1;
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JLabel CategoryLabelItem;
    private javax.swing.JPanel CurrentSitePanel;
    private javax.swing.JPanel CurrentSupplierPanel;
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel InformationLabelItem;
    private javax.swing.JTextField InformationTextField;
    private javax.swing.JButton ItemButton;
    private javax.swing.JLabel ItemNameLabelItem;
    private javax.swing.JTextField ItemNameTextField;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JTable ItemResultTable;
    private javax.swing.JScrollPane ItemsScrollPane;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTabbedPane ManagementTabber;
    private javax.swing.JButton PaymentButton;
    private javax.swing.JPanel PaymentPanel;
    private javax.swing.JTabbedPane PaymentTabber;
    private javax.swing.JTabbedPane PendingTabber;
    private javax.swing.JLabel PriceLabelItem;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JCheckBox RestrictedCheckBox;
    private javax.swing.JLabel RestrictedLabelItem;
    private javax.swing.JButton SearchItemButtonItem;
    private javax.swing.JTextField SearchItemTextfieldItem;
    private javax.swing.JLabel SelectSiteLabel;
    private javax.swing.JLabel SelectSupplierLabel;
    private javax.swing.JPanel SiteAddUpdatePanel;
    private javax.swing.JLabel SiteAddressLabel;
    private javax.swing.JTextField SiteAddressTextField;
    private javax.swing.JButton SiteButton;
    private javax.swing.JLabel SiteCurrentCapacityLabel;
    private javax.swing.JTextField SiteCurrentCapacityTextField;
    private javax.swing.JList<String> SiteList;
    private javax.swing.JComboBox<String> SiteManagerComboBox;
    private javax.swing.JLabel SiteManagerLabel;
    private javax.swing.JLabel SiteNameLabel;
    private javax.swing.JTextField SiteNameTextField;
    private javax.swing.JPanel SitePanel;
    private javax.swing.JLabel SiteStorageCapacityLabel;
    private javax.swing.JTextField SiteStorageCapacityTextField;
    private javax.swing.JButton SiteUpdateButton;
    private javax.swing.JLabel SubHeaderLabelItem;
    private javax.swing.JLayeredPane SubPanels;
    private javax.swing.JTabbedPane SuccessfulPaymentTabber;
    private javax.swing.JPanel SupplierAddUpdatePanel;
    private javax.swing.JLabel SupplierAddressLabel;
    private javax.swing.JTextField SupplierAddressTextField;
    private javax.swing.JLabel SupplierBankNoLabel;
    private javax.swing.JTextField SupplierBankNoTextField;
    private javax.swing.JButton SupplierButton;
    private javax.swing.JLabel SupplierEmailLabel;
    private javax.swing.JTextField SupplierEmailTextField;
    private javax.swing.JList<String> SupplierList;
    private javax.swing.JLabel SupplierNameLabel;
    private javax.swing.JTextField SupplierNameTextField1;
    private javax.swing.JPanel SupplierPanel;
    private javax.swing.JLabel SupplierPhoneLabel;
    private javax.swing.JTextField SupplierPhoneNoTextField;
    private javax.swing.JButton SupplierUpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
